Quiz/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("", include("Quizlet.urls")),
    path("admin/", admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

Quizlet/urls.py
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from Quiz.sitemaps import QuizSitemap
from . import views

app_name = 'quizlet'

sitemaps = {
    'posts': QuizSitemap,
}

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:id>/", views.detail, name='detail'),
    path('<int:id>', views.post_comment, name='post_comment'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap')
    
]

bLOGE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Quizlet/models.py
from django.db import models
from django.urls import reverse



class Quiz(models.Model):
    question_text = models.CharField(max_length=100, verbose_name='Тема квиза')


    def get_absolute_url(self):
        return reverse("quizlet:detail", args=[self.id])

    def __str__(self):
        return self.question_text
    
    class Meta:
        db_table_comment= "Тут у нас храняться темы квиза"
        verbose_name = 'Квиз'
        verbose_name_plural = 'Квизы'
        

        

class Question(models.Model):
    class Status(models.TextChoices):
        PROPERLY = 'PR', 'properly'
        WRONG = 'WR', "wrong"
        
    quiz = models.ForeignKey(Quiz, verbose_name="Вопросики", on_delete=models.CASCADE)
    question = models.CharField(max_length=100, unique=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.WRONG)
    
    def __str__(self):
        return f"{self.question}"
    
    
class Comment(models.Model):
    quize = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=20)
    body = models.TextField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

Quizlet/forms.py
from django.forms import ModelForm
from .models import Quiz, Question, Comment

class QuizForm(ModelForm):
    class Meta:
        model = Quiz
        fields = ['question_text']
        
class QuestionForm(ModelForm):
    class  Meta:
        model = Question
        fields = ['question', 'status']        
        
class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'body']        

Quizlet/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from .models import Quiz, Question, Comment
from django.http import Http404
from .forms import QuizForm, QuestionForm, CommentForm
from django.urls import reverse
from django.core.paginator import Paginator
from django.views.decorators.http import require_POST


def index(request):
    if request.method == "POST":
        forma = QuizForm(request.POST)
        if forma.is_valid():
            forma.save()
            HttpResponseRedirect('/')
    else:
        forma = QuizForm()
    
    context = Quiz.objects.all().order_by('-id')  
    paginator = Paginator(context, 3)
    page_number = request.GET.get('page', 1)
    posts = paginator.page(page_number)
     
    return render(request, "Quizlet/index.html", {"latest_question_list": posts,'forma': forma })




def detail(request, id):
    some = Question.objects.filter(quiz=id)
    qizi = Quiz.objects.get(id=id)
    commentform = CommentForm()
    comments = Comment.objects.filter(quize=qizi)
    if request.method == "POST":
        answerform = QuestionForm(request.POST)
        if answerform.is_valid():
            answer = answerform.save(commit=False)
            answer.quiz = qizi
            answer.save()
            return HttpResponseRedirect(reverse('quizlet:detail', args=[id]))
    else:
        answerform = QuestionForm()
    return render(request, 'Quizlet/detail.html', {'form': answerform, "questions":some, "qizi":qizi, "commentform":commentform,"comments":comments,})


@require_POST
def post_comment(request, id):
    qizi = Quiz.objects.get(id=id)
    comment = None
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.quize = qizi
        comment.save()
    return render(request,  'Quizlet/comment.html', {"commentform":form,"comment":comment, "qizi":qizi})

templates/Quizlet/comment.html
Add a comment


{% if comment %}
    <h2>Your comment has been added.</h2>
{% else %}
    {% include "Qizlet/comment_form.html" %}
{% endif %}
<p><a href="{{ qizi.get_absolute_url }}">Вернуться к квизу</a></p>

templates/Quizlet/comment_form.html
<h2>Add a new comment</h2>
<form action="{% url 'quizlet:post_comment' qizi.id %}" method="post">
    {% csrf_token %}
    {{ commentform.as_p }}
    <p><input type="submit" value="Add comment"></p>
</form>

templates/Quizlet/detail.html
<button onclick="window.location.href='{% url 'quizlet:index' %}'" class="btn btn-primary">
    Главное меню
</button>

<a>{{qizi}}</a>

<form action="{% url 'quizlet:detail' qizi.id %}" method='post'>
    {% csrf_token %}
    <table>
    {{form.as_table}}
    </table>
    <input type="submit" value="Submit">
</form>
{% if questions %}
    <ul>
    {% for con in questions %}
        <li>
            <a>{{con.question}}</a> Статус - <a>{{con.status}}</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>Вопросов нет</p>
{% endif %}

{% with comments.count as total_comments %}
    <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
{% endwith %}

{% for comment in comments %}
    <div class="comment">
        <p class="info">
            Comment {{ forloop.counter }} by {{ comment.name }}
            {{ comment.created }}
        </p>
        {{ comment.body|linebreaks }}
    </div>
{% empty %}
    <p>There are no comments.</p>
{% endfor %}
{% include "Quizlet/comment_form.html" %}

templates/Quizlet/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{{question.get_absolute_url}}">  {{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Нет тем квизов</p>
{% endif %}
<form action={%url 'quizlet:index' %} method='post'>
    {% csrf_token %}
    <table>
    {{forma.as_table}}
    </table>
    <input type="submit" value="Submit">
</form>

<div id="content">
    {% block content %}
    {% endblock %}
</div>
{% include 'Quizlet/paginator.html' with page=latest_question_list %}


<hr>
{% if user.is_authenticated %}
    Hi {{ user.username }}!
<form action="{% url 'logout' %}" method="post">
    {% csrf_token %}
    <a href="#" onclick="parentNode.submit();">Log Out</a>
</form>
{% else %}
    <p>You are not logged in</p>
    <a href="{% url 'login' %}">Log In</a>
{% endif %}
<hr>

templates/Quizlet/paginator.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %} <!-- если есть предыдущая страница, то показываем её кнопку -->
            <a href="?page={{ page.previous_page_number }}">Previous</a> <!-- возвращает номер предыдущей страницы -->
        {% endif %}
        <span class="current">
           Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %} <!-- если есть следующая страница, то показываем её кнопку -->
            <a href="?page={{ page.next_page_number }}">Next</a> <!-- возвращает номер следующей страницы -->
        {% endif %}
    </span>
</div>